### ISSUE TITLE
on-load-more not fired when the element has padding

### ISSUE THREAD

**Issue by JordanVincent** [amk221/ember-simple-infinite-scroller#1]
When using the infinite-scroller component with `use-document=false` and padding `.infinite-scroller: { padding: 15px; }`, `on-load-more` is not fired. It's because the height returned by `_scrollerHeight` is not taking into account padding. A way to fix it is just to use jQuery's `outerHeight` function like so:

```js
// addon/components/infinite-scroller.js

_scrollerHeight() {
  if (this.getAttr('use-document')) {
    return this.get('_infiniteScroller').$window().outerHeight();
  } else {
    return this.$scroller().outerHeight();
  }
}
```

**Comment by amk221** [comment]
Right ho, sure.
I'll add a test and look at getting it fixed

**Comment by JordanVincent** [comment]
That was fast! Thanks so much :)
