### ISSUE TITLE
Can we make it stop calling loadMore if RSVP.reject() is returned?

### ISSUE THREAD

**Issue by joshuairl** [amk221/ember-simple-infinite-scroller#2]

**Comment by amk221** [comment]
Hi @joshuairl. I don't think so....
`on-load-more` will fire whenever the bottom is scrolled to...
It has nothing to do with whether or not your action will be successful or not.

If you fancy giving me your use case that could help, perhaps I've misunderstood. Cheers

**Comment by amk221** [comment]
Bump
