### ISSUE TITLE
Not working with bootstrap scrollspy

### ISSUE THREAD

**Issue by zengoma** [amk221/ember-simple-infinite-scroller#3]
Hi. Thanks for this ember add-on. I'm having difficulty using it in conjunction with bootstrap scroll-spy. Here is my template markup.

```
 <div class="scroll-watcher" data-spy="scroll" data-target="list-group">    
            <div class="list-group">
            {{#infinite-scroller on-load-more=(action 'nextPage') as |scroller|}}
                {{#each model as |material|}}
                        {{#link-to "materials.detail" material class="list-group-item"}}
                                <span class="badge">{{material.code}}</span>
                                <h4 class="list-group-item-heading">{{material.name}}</h4>
                                <p class="list-group-item-text">
                                    {{material.category.value}}
                                </p>
                        {{/link-to}}
                {{/each}}
            {{/infinite-scroller}}
            </div>     
        </div>
```
The nextPage action is not triggered when I reach the bottom of the scroll box. I know my controller action setup is working fine when I set use-document=true and scroll to the bottom of the page the action triggers correctly. I need to get it working on my bootstrap scroll box though? Is this an issue or have I just done something silly.

**Comment by amk221** [comment]
Can you replicate it for me in a Twiddle?
I've done some groundwork, but if you could make it fail that would help, cheers:

https://ember-twiddle.com/f83ebcd9809a161dc8475b35a83a3700?openFiles=templates.application.hbs%2C

**Comment by zengoma** [comment]
@amk221 , Thank you for the response. I immediately discovered my error when looking at the ember twiddle you set up. I did not declare the .infinite-scroller class in my app.css. It now works perfectly. Is it possible to define a custom css target besides .infinite-scroller? The documentation seems to suggest there is but I can't quite figure it out? None the less, thank you for your assistance. Please go ahead and close this issue after your response. It turned out to be no issue at all, just human error.

**Comment by amk221** [comment]
Sure, you can't remove `infinite-scroller` class, but you can add another one with 
```handlebars
{{infinite-scroller class="my-class"`}}
```
